// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import KeywordsController from "./keywords_controller"
application.register("keywords", KeywordsController)

import LoginDialogController from "./login_dialog_controller"
application.register("login-dialog", LoginDialogController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ThreejsController from "./threejs_controller"
application.register("threejs", ThreejsController)
